name: Pull Request linode-dns-go/seannguyen.dev
on:
  pull_request:
    paths:
      - 'linode-dns-go/**'
      - '.github/workflows/pr_dns_seannguyen_dev.yml'
    branches:
      - main

defaults:
  run:
    working-directory: ./linode-dns-go

jobs:
  preview:
    name: Preview seannguyen.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - run: go mod download
      - run: ls
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: seannguyen.dev
          comment-on-pr: true
          work-dir: ./linode-dns-go
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_K8s_HELM_REPOSITORY_CACHE: ${{ env.RUNNER_TEMP }}
